paths:

    -   description: handles core requirements
        type: (dev|test)-requirements.txt
        path: cloudify.*
        match: 'https\://github\.com/cloudify-cosmo/cloudify-.+(\@.*#egg|/archive/.*)'
        replace: '(master|(\d+)(\.\d+){1,2}(dev|(\w+(\d+)?)?))'
        with: "{{ .yaml_core_version }}"

    -   description: handles plugin requirements
        type: (dev|test)-requirements.txt
        path: cloudify.*
        match: 'https\://github\.com/cloudify-cosmo/cloudify-.+-plugin(\@.*#egg|/archive/.*)'
        replace: '(\d+)(\.\d+){1,2}(dev|(\w+(\d+)?)?)'
        with: "{{ .yaml_plugins_version }}"

    -   description: handles core requirements
        path: cloudify-packager/docker/vars.py
        match: '"cloudify_.+": "git\+git://github\.com/cloudify-cosmo/cloudify-.+\@.*",'
        replace: '(master|(\d+)(\.\d+){1,2}(dev|(\w+(\d+)?)?))'
        with: "{{ .yaml_core_version }}"

    -   description: handles plugin requirements
        path: cloudify-packager/docker/vars.py
        match: '"cloudify_.+": "git\+git://github\.com/cloudify-cosmo/cloudify-.*-plugin.*"'
        replace: '(\d+)(\.\d+){1,2}(dev|(\w+(\d+)?)?)'
        with: "{{ .yaml_plugins_version }}"

    -   description: handles core requirements
        path: cloudify-packager/docker/vars.py
        match: '-b master https://github\.com/cloudify-cosmo/cloudify-.+.git'
        replace: '(master|(\d+)(\.\d+){1,2}(dev|(\w+(\d+)?)?))'
        with: "{{ .yaml_core_version }}"

    -   decription: handles core requirements
        path: cloudify-packager/docker/vars.py
        match: 'https://raw.githubusercontent.com/cloudify-cosmo/cloudify-manager/master/plugins/riemann-controller/riemann_controller/resources/manager.config'
        replace: '\/(master|(\d+)(\.\d+){1,2}(dev|(\w+(\d+)?)?))\/'
        with: "/{{ .yaml_core_version }}/"

    # Update inscript references
    -   description: Replace inscript references
        path: ../cloudify-manager/resources/rest-service/cloudify/types/types.yaml
        match: cloudify-cosmo/cloudify-manager/master
        replace: master
        with: "{{ .yaml_core_version }}"
